version: '3.6'

volumes:
  exec_data:

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - default
  qiskit-service:
    image: planqk/qiskit-service:latest
    command: sh /app/startup.sh
    ports:
      - "5000:5000"
    environment:
      - REDIS_URL=redis://redis
      - DATABASE_URL=sqlite:////data/app.db
    volumes:
      - exec_data:/data
    networks:
      - default

  rq-worker:
    image: planqk/qiskit-service:latest
    command: rq worker --url redis://redis qiskit-service_execute
    environment:
      - REDIS_URL=redis://redis
      - DATABASE_URL=sqlite:////data/app.db
    volumes:
      - exec_data:/data
    depends_on:
      - redis
    deploy:
      replicas: 4

  
  rq-dashboard:
    image: eoranged/rq-dashboard
    ports:
      - "9181:9181"
    environment:
      - RQ_DASHBOARD_REDIS_URL=redis://redis:6379

networks:
  default:
    driver: bridge
