"""empty message

Revision ID: 13d46ba5b86f
Revises: f080730a59e6
Create Date: 2024-06-26 11:57:17.586499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13d46ba5b86f'
down_revision = 'f080730a59e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'result', 'generated__circuit', ['generated_circuit_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'result', type_='foreignkey')
    # ### end Alembic commands ###
