"""empty message

Revision ID: 16025439793c
Revises: 4b97708bd5be
Create Date: 2024-05-17 14:52:55.180222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16025439793c'
down_revision = '4b97708bd5be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated__circuit',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('generated_circuit', sa.String(length=1200), nullable=True),
    sa.Column('input_params', sa.String(length=1200), nullable=True),
    sa.Column('original_depth', sa.Integer(), nullable=True),
    sa.Column('original_width', sa.Integer(), nullable=True),
    sa.Column('original_total_number_of_operations', sa.Integer(), nullable=True),
    sa.Column('original_number_of_multi_qubit_gates', sa.Integer(), nullable=True),
    sa.Column('original_number_of_measurement_operations', sa.Integer(), nullable=True),
    sa.Column('original_number_of_single_qubit_gates', sa.Integer(), nullable=True),
    sa.Column('original_multi_qubit_gate_depth', sa.Integer(), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('generated__circuit')
    # ### end Alembic commands ###
