"""empty message

Revision ID: 2b46d0dbaf75
Revises: 16025439793c
Create Date: 2024-06-03 12:06:05.777967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b46d0dbaf75'
down_revision = '16025439793c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('result', sa.Column('generated_circuit_id', sa.String(length=36), nullable=True))
    op.add_column('result', sa.Column('post_processing_result', sa.String(length=1200), nullable=True))
    op.create_foreign_key(None, 'result', 'generated__circuit', ['generated_circuit_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'result', type_='foreignkey')
    op.drop_column('result', 'post_processing_result')
    op.drop_column('result', 'generated_circuit_id')
    # ### end Alembic commands ###
