"""remove counts again

Revision ID: 48f06b6bbb8f
Revises: 696b3aebedd3
Create Date: 2021-11-06 12:38:20.472531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48f06b6bbb8f'
down_revision = '696b3aebedd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result') as batch_op:
        batch_op.drop_column('counts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('result', sa.Column('counts', sa.VARCHAR(length=1200), nullable=True))
    # ### end Alembic commands ###
