"""empty message

Revision ID: 4b1204825905
Revises: 1fc6ec75c3a1
Create Date: 2021-12-08 15:11:24.176357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b1204825905'
down_revision = '1fc6ec75c3a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('benchmark', sa.Column('original_number_of_multi_qubit_gates', sa.Integer(), nullable=True))
    op.add_column('benchmark', sa.Column('transpiled_number_of_multi_qubit_gates', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('benchmark', 'transpiled_number_of_multi_qubit_gates')
    op.drop_column('benchmark', 'original_number_of_multi_qubit_gates')
    # ### end Alembic commands ###
