"""empty message

Revision ID: 4b97708bd5be
Revises: 4b1204825905
Create Date: 2022-05-30 14:07:52.389380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b97708bd5be'
down_revision = '4b1204825905'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('benchmark', sa.Column('clifford', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('benchmark', 'clifford')
    # ### end Alembic commands ###
