"""empty message

Revision ID: 696b3aebedd3
Revises: d2b348622bf7
Create Date: 2021-11-06 11:26:23.700044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '696b3aebedd3'
down_revision = 'd2b348622bf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('result', sa.Column('backend', sa.String(length=1200), nullable=True))
    op.add_column('result', sa.Column('counts', sa.String(length=1200), nullable=True))
    op.add_column('result', sa.Column('shots', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('result', 'shots')
    op.drop_column('result', 'counts')
    op.drop_column('result', 'backend')
    # ### end Alembic commands ###
