"""empty message

Revision ID: f080730a59e6
Revises: 2b46d0dbaf75
Create Date: 2024-06-03 12:06:23.002582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f080730a59e6'
down_revision = '2b46d0dbaf75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'result', 'generated__circuit', ['generated_circuit_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'result', type_='foreignkey')
    # ### end Alembic commands ###
